/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as HealthRouteImport } from './routes/health'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as AdminLoginRouteImport } from './routes/admin_.login'
import { Route as ApiRealtimeRouteImport } from './routes/api.realtime'
import { Route as SitesSlugRouteImport } from './routes/sites.$slug'
import { Route as ThumbnailsKeyRouteImport } from './routes/thumbnails.$key'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRealtimeRoute = ApiRealtimeRouteImport.update({
  id: '/api/realtime',
  path: '/api/realtime',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesSlugRoute = SitesSlugRouteImport.update({
  id: '/sites/$slug',
  path: '/sites/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ThumbnailsKeyRoute = ThumbnailsKeyRouteImport.update({
  id: '/thumbnails/$key',
  path: '/thumbnails/$key',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/health': typeof HealthRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tags': typeof TagsRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/realtime': typeof ApiRealtimeRoute
  '/sites/$slug': typeof SitesSlugRoute
  '/thumbnails/$key': typeof ThumbnailsKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/health': typeof HealthRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tags': typeof TagsRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/realtime': typeof ApiRealtimeRoute
  '/sites/$slug': typeof SitesSlugRoute
  '/thumbnails/$key': typeof ThumbnailsKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/health': typeof HealthRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tags': typeof TagsRoute
  '/admin_/login': typeof AdminLoginRoute
  '/api/realtime': typeof ApiRealtimeRoute
  '/sites/$slug': typeof SitesSlugRoute
  '/thumbnails/$key': typeof ThumbnailsKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/health'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/tags'
    | '/admin/login'
    | '/api/realtime'
    | '/sites/$slug'
    | '/thumbnails/$key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/health'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/tags'
    | '/admin/login'
    | '/api/realtime'
    | '/sites/$slug'
    | '/thumbnails/$key'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/health'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/tags'
    | '/admin_/login'
    | '/api/realtime'
    | '/sites/$slug'
    | '/thumbnails/$key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  HealthRoute: typeof HealthRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TagsRoute: typeof TagsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ApiRealtimeRoute: typeof ApiRealtimeRoute
  SitesSlugRoute: typeof SitesSlugRoute
  ThumbnailsKeyRoute: typeof ThumbnailsKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/realtime': {
      id: '/api/realtime'
      path: '/api/realtime'
      fullPath: '/api/realtime'
      preLoaderRoute: typeof ApiRealtimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/$slug': {
      id: '/sites/$slug'
      path: '/sites/$slug'
      fullPath: '/sites/$slug'
      preLoaderRoute: typeof SitesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thumbnails/$key': {
      id: '/thumbnails/$key'
      path: '/thumbnails/$key'
      fullPath: '/thumbnails/$key'
      preLoaderRoute: typeof ThumbnailsKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  HealthRoute: HealthRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TagsRoute: TagsRoute,
  AdminLoginRoute: AdminLoginRoute,
  ApiRealtimeRoute: ApiRealtimeRoute,
  SitesSlugRoute: SitesSlugRoute,
  ThumbnailsKeyRoute: ThumbnailsKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
